### ISSUE TITLE
Spark's `from_csv` method has difficulty with some odd unicode characters

### ISSUE THREAD

**Issue by okennedy** [UBOdin/mimir-api#9]
Reproducible test case here: https://github.com/UBOdin/mimir-api/blob/add-dataset-properties/src/test/scala/org/mimirdb/data/SafelyLoadFunkyData.scala#L47

This test case came from Vizier, where it's being used to evaluate the ability to load CSV files with garbage unicode data.  I'm not 100% sure where it is, but the simple checks have turned up nothing and it really does seem to be some underlying issue within spark.  Based on the traces, it looks like Spark uses a [`StringLike`](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/StringLike.scala) internally, and the StringLike's `toString` method is returning null. I was under the impression that the specific `StringLike` used during execution is [`UTF8String`](https://github.com/apache/spark/blob/master/common/unsafe/src/main/java/org/apache/spark/unsafe/types/UTF8String.java), but that doesn't seem to be the case, since the corresponding `toString` method always returns a `new String(...)`.  Unfortunately, the stack trace doesn't give any insight into which StringLike is actually being used.

I'm pausing investigations for now, but here's a stack trace

```
19:01:11.511 [Executor task launch worker for task 553] ERROR org.apache.spark.executor.Executor - Exception in task 1.0 in stage 135.0 (TID 553)
java.lang.NullPointerException: null
	at scala.collection.immutable.StringLike.stripLineEnd(StringLike.scala:93)
	at scala.collection.immutable.StringLike.stripLineEnd$(StringLike.scala:92)
	at scala.collection.immutable.StringOps.stripLineEnd(StringOps.scala:33)
	at org.apache.spark.sql.catalyst.csv.UnivocityParser.getCurrentInput(UnivocityParser.scala:88)
	at org.apache.spark.sql.catalyst.csv.UnivocityParser.$anonfun$convert$1(UnivocityParser.scala:218)
	at org.apache.spark.sql.catalyst.util.FailureSafeParser.$anonfun$toResultRow$1(FailureSafeParser.scala:50)
	at org.apache.spark.sql.catalyst.util.FailureSafeParser.parse(FailureSafeParser.scala:64)
	at org.apache.spark.sql.catalyst.expressions.CsvToStructs.nullSafeEval(csvExpressions.scala:131)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:322)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:444)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19:01:11.511 [Executor task launch worker for task 552] ERROR org.apache.spark.executor.Executor - Exception in task 0.0 in stage 135.0 (TID 552)
java.lang.NullPointerException: null
	at scala.collection.immutable.StringLike.stripLineEnd(StringLike.scala:93)
	at scala.collection.immutable.StringLike.stripLineEnd$(StringLike.scala:92)
	at scala.collection.immutable.StringOps.stripLineEnd(StringOps.scala:33)
	at org.apache.spark.sql.catalyst.csv.UnivocityParser.getCurrentInput(UnivocityParser.scala:88)
	at org.apache.spark.sql.catalyst.csv.UnivocityParser.$anonfun$convert$1(UnivocityParser.scala:218)
	at org.apache.spark.sql.catalyst.util.FailureSafeParser.$anonfun$toResultRow$1(FailureSafeParser.scala:50)
	at org.apache.spark.sql.catalyst.util.FailureSafeParser.parse(FailureSafeParser.scala:64)
	at org.apache.spark.sql.catalyst.expressions.CsvToStructs.nullSafeEval(csvExpressions.scala:131)
	at org.apache.spark.sql.catalyst.expressions.UnaryExpression.eval(Expression.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:322)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:872)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:872)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:349)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:313)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:444)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19:01:11.535 [task-result-getter-2] ERROR o.a.spark.scheduler.TaskSetManager - Task 1 in stage 135.0 failed 1 times; aborting job
```

**Comment by okennedy** [comment]
There were a few recent changes, including a switch to a safer mimir-backed CSV parser.  This issue no longer occurs.
